---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
  - name: Test login
    uri:
      url: http://0.0.0.0:5601/login
      status_code: 200
    register: web_login
    until: web_login.status == 200
    retries: 60
    delay: 1
  - name: Logs exists
    stat:
      path: /var/log/kibana.log
    register: log_exist_result
